# Generated by Django 4.0 on 2022-01-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Оператор')),
                ('model_car', models.CharField(max_length=255, verbose_name='Модель машины')),
                ('number_car', models.CharField(max_length=255, verbose_name='Номер машины')),
                ('sum', models.CharField(max_length=255, verbose_name='Сумма')),
                ('image', models.ImageField(upload_to='posts/images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Данные авто',
                'verbose_name_plural': 'Добавить',
            },
        ),
    ]
