# Generated by Django 3.2.9 on 2022-01-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_delete_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/car_icon.png', null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='post',
            name='service',
            field=models.CharField(default=1, max_length=255, verbose_name='Вид услуги'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Мойщик'),
        ),
    ]
